[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
fancy-regex="0.16.2"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "day_1"
harness = false

[[bench]]
name = "day_2"
harness = false
